/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/

// CREATE CONFIG OBJECT

exports.settings = {
  salt: "sjstudios",
  hashOptions: {
    digest: "sha512",
    hashBytes: 512,
    saltBytes: 256,
    iterations: 100000
  }
};
