/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/
module.exports = function (service) {

  service.endpoint('get', null, function (req, res) {
    res.json(service.responseEnvelope());
  });

  service.endpoint('post', null, function (req, res) {
		service.getProfile(req.body, function (results) {
      res.json(service.responseEnvelope('', results));
    });
  });

  service.endpoint('post', '/avatar', function (req, res) {
		service.getAvatar(req.body, function (results) {
      res.json(service.responseEnvelope('/avatar', results));
    });
  });

  service.endpoint('post', '/friendrequests', function (req, res) {
		service.getFriendRequests(req.body, function (results) {
      res.json(service.responseEnvelope('/friendrequests', results));
    });
  });
};
