/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/
module.exports = function (service) {

  service.endpoint('get', null, function (req, res) {
    res.json(service.responseEnvelope());
  });

  service.endpoint('post', null, function (req, res) {
    if (typeof(req.body.locationId) === 'undefined') {
      res.json(service.responseEnvelope());
    } else {
      service.getMapNodes(req.body, function (results) {
        res.json(service.responseEnvelope('', results));
      });
    }
  });

  service.endpoint('post', '/bundle', function (req, res) {
    if (typeof(req.body.locationId) === 'undefined') {
      res.json(service.responseEnvelope());
    } else {
      service.getDataBundle(req.body, function (results) {
        res.json(service.responseEnvelope('/bundle', results));
      });
    }
  });

  service.endpoint('post', '/subdivision', function (req, res) {
    if (typeof(req.body.subDivisionId) === 'undefined') {
      res.json(service.responseEnvelope());
    } else {
      service.getMapSubDivision(req.body, function (results) {
        res.json(service.responseEnvelope('/subdivision', results));
      });
    }
  });

  service.endpoint('post', '/heatmap', function (req, res) {
		service.getHeatMap(req.body, function (results) {
      res.json(service.responseEnvelope('/heatmap', results));
    });
  });

  service.endpoint('post', '/geojson', function (req, res) {
		service.getJsonLayer(req.body, function (results) {
      res.json(service.responseEnvelope('/geojson', results));
    });
  });

  service.endpoint('post', '/location', function (req, res) {
    if (typeof(req.body.userLat) === 'undefined' || typeof(req.body.userLon) === 'undefined') {
      res.json(service.responseEnvelope());
    } else {
      service.getAnonymousLocation(req.body, function (results) {
        res.json(service.responseEnvelope('/location', results));
      });
    }
  });

  service.endpoint('post', '/events', function (req, res) {
		service.getEventList(req.body, function (results) {
      res.json(service.responseEnvelope('/events', results));
    });
  });
};
