/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/
module.exports = function (service) {

  service.endpoint('get', null, function (req, res) {
    res.json(service.responseEnvelope());
  });

  service.endpoint('post', null, function (req, res) {
		service.getChatFeed(req.body, function (results) {
      res.json(service.responseEnvelope('', results));
    });
  });

  service.endpoint('post', '/preview', function (req, res) {
		service.getChatPreview(req.body, function (results) {
      res.json(service.responseEnvelope('/preview', results));
    });
  });

  service.endpoint('post', '/eventpreview', function (req, res) {
		service.getEventPreview(req.body, function (results) {
      res.json(service.responseEnvelope('/eventpreview', results));
    });
  });
};
