/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/
module.exports = function (service) {

  service.endpoint('get', null, function (req, res) {
    res.json(service.responseEnvelope());
  });

  service.endpoint('post', null, function (req, res) {
    var input = {
      userName: req.body.userName,
      passWord: req.body.passWord,
      ipAddress: req.ip
    };
		service.userLogin(input, function (results) {
      res.json(service.responseEnvelope('', results));
    });
  });

  service.endpoint('post', '/logout', function (req, res) {
    var input = {
      userId: req.body.userId,
      userName: req.body.userName,
      ipAddress: req.ip
    };
		service.userLogout(input, function (results) {
      res.json(service.responseEnvelope('/logout', results));
    });
  });

  service.endpoint('post', '/token', function (req, res) {
    var input = {
      userName: req.body.userName,
      token: req.body.token,
      ipAddress: req.ip
    };
		service.userTokenLogin(input, function (results) {
      res.json(service.responseEnvelope('/token', results));
    });
  });

  // service.endpoint('get', '/test/:username', function (req, res) {
  //   var un = req.params.username;
	// 	service.findUser(un, function (results) {
  //     results.uri = service.URI;
  //     res.json(results);
  //   });
  // });
  //
  // service.endpoint('get', '/:username/:password', function (req, res) {
  //   var un = req.params.username,
  //   pw = req.params.password;
	// 	service.userLogin(un, pw, function (results) {
  //     results.uri = service.URI;
  //     res.json(results);
  //   });
  // });
};
