/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/
module.exports = function (service) {

  service.endpoint('get', null, function (req, res) {
    res.json(service.responseEnvelope());
  });

  service.endpoint('post', null, function (req, res) {
    service.getProfile(req.body, function (results) {
      res.json(service.responseEnvelope('', results));
    });
  });

  service.endpoint('get', '/getrunning', function (req, res) {
    res.json(service.responseEnvelope());
  });

  service.endpoint('options', '/getrunning', function (req, res) {
    res.json(service.responseEnvelope());
  });
};
