/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/
module.exports = function (service) {

  service.endpoint('get', null, function (req, res) {
    res.json(service.responseEnvelope());
  });

  service.endpoint('post', null, function (req, res) {
		service.updateProfile(req.body, function (results) {
      res.json(service.responseEnvelope('', results));
    });
  });

  service.endpoint('post', '/avatar', function (req, res) {
		service.updateAvatar(req.body, function (results) {
      res.json(service.responseEnvelope('/avatar', results));
    });
  });

  service.endpoint('post', '/status', function (req, res) {
		service.updateStatus(req.body, function (results) {
      res.json(service.responseEnvelope('/status', results));
    });
  });

  service.endpoint('post', '/hometown', function (req, res) {
		service.updateHometown(req.body, function (results) {
      res.json(service.responseEnvelope('/hometown', results));
    });
  });

  service.endpoint('post', '/location', function (req, res) {
    if (typeof(req.body.userId) === 'undefined' || typeof(req.body.userLat) === 'undefined' || typeof(req.body.userLon) === 'undefined') {
      res.json(service.responseEnvelope());
    } else {
      service.updateLocation(req.body, function (results) {
        res.json(service.responseEnvelope('/location', results));
      });
    }
  });

  service.endpoint('post', '/sendfriendrequest', function (req, res) {
		service.sendFriendRequest(req.body, function (results) {
      res.json(service.responseEnvelope('/sendfriendrequest', results));
    });
  });

  service.endpoint('post', '/updatefriendrequest', function (req, res) {
		service.updateFriendRequest(req.body, function (results) {
      res.json(service.responseEnvelope('/updatefriendrequest', results));
    });
  });
};
